package io.github.eisop.runtimeframework.util;

import io.github.eisop.runtimeframework.core.RuntimeInstrumenter;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.TypeKind;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;

/**
 * A concrete instrumenter used for testing and debugging. It injects a System.out.println at the
 * start of every method.
 */
public class SysOutInstrumenter extends RuntimeInstrumenter {

  public SysOutInstrumenter() {
    super();
  }

  /**
   * Generates bytecode instructions to print a diagnostic message to standard output.
   *
   * <p>The generated bytecode corresponds to the Java statement:
   *
   * <pre>{@code
   * System.out.println("RuntimeCheck: Verifying param at slot " + slotIndex);
   * }</pre>
   *
   * <p>This implementation ignores the actual type of the parameter and simply reports which slot
   * is being visited.
   *
   * @param b the {@link CodeBuilder} used to emit the bytecode instructions
   * @param slotIndex the local variable slot index of the parameter currently being "checked"
   * @param type the {@link TypeKind} of the parameter (unused in this implementation, but required
   *     by the contract)
   */
  @Override
  protected void generateCheck(CodeBuilder b, int slotIndex, TypeKind type) {
    b.getstatic(ClassDesc.of("java.lang.System"), "out", ClassDesc.of("java.io.PrintStream"));
    b.ldc("RuntimeCheck: Verifying param at slot " + slotIndex);
    b.invokevirtual(
        ClassDesc.of("java.io.PrintStream"),
        "println",
        MethodTypeDesc.ofDescriptor("(Ljava/lang/String;)V"));
  }
}
